train:
    learning_rate: 0.001
    epochs: 1
    batch_size: 128
    device: "cuda"

audio:
    sample_rate: 16000
    num_mels: 64
    frame_step: 160

dataset:
    path: "/home/kar/Projects/EEND_SelfAttention/EEND_SelfAttention/data/merged_data"
    num_speakers: 4
    frame_duration: 0.01

model:
    hidden_dim: 128
    num_heads: 4
